### ISSUE TITLE
Multiple PositionSensorVRDevices at once

### ISSUE THREAD

**Issue by borismus** [MozVR/webvr-spec#2]
Multiple position sensors controlling the observer seems to be a common situation. 

Most commonly, you may be using the Rift's gyroscope for rotation, but also want to support mouse look and maybe arrow keys to look around.

Also, I'd like to build a 6DOF system for desktop where we use [headtrackr](http://topheman.github.io/parallax/) for the positional DOFs, but also be able to mouse look. This case is easier since one of the devices only provides rotation, and the other provides only position.

Looks like the spec intends VRPositionState to report in absolute coordinates, which makes it hard to combine multiple states (eg. the rift case). Maybe switching to relative would be helpful for this? Otherwise how do we handle the multiple position sensor case?

**Comment by brianpeiris** [comment]
See also mrdoob/three.js#6286.

**Comment by jbaicoianu** [comment]
Another good use for multiple PositionSensorVRDevices will be for input systems like Oculus Touch and Valve's Lighthouse.  These controllers will likely provide the same position and orientation data as HMDs, in addition to button and axis data which can be represented using the Gamepad API as they would be today.  

In these cases we'd probably want the data to be in global space (basically whatever the tracking system's coordinate space is), since the position of the separate tracked objects is not really tied to any specific HMD's orientation.

**Comment by toji** [comment]
Issue is no longer relevant with upcoming API changes. Closing.
